### ISSUE TITLE
UI: devices and sessions Ordering is not working (pagination is not working properly)

### ISSUE THREAD

**Issue by S-Chinthana** [shellhub-io/shellhub#79]
HI, Shellhub v0.2.4 is now working flawlessly, but there is some sort of UI issues on v0.2.4-UI. Now In new version device page and session page have pagination in it. but we can’t sort it according to ascending or descending order. Ordering is not working. 

In the session page, first, it shows the oldest session. I think this can be a small issue. also can't load all sessions into one page.  And I think it'll be much convenient if the number of items per page has a selection like [10, 20, 50, all] rather than [5,10,15, all].

**Comment by gustavosbarreto** [comment]
Hi @S-Chinthana,
We're happy with your feedback.

> Now In new version device page and session page have pagination in it. but we can’t sort it according to ascending or descending order. Ordering is not working.

For now, we are considering to disable sorting in the UI because the backend doesn't support it. In a future release, we will support sorting sessions and devices properly.

> In the session page, first, it shows the oldest session. I think this can be a small issue. 

Fixed in f28c918c6a085035818a4a2235511b0c91ccf4db

> And I think it'll be much convenient if the number of items per page has a selection like [10, 20, 50, all] rather than [5,10,15, all].

I agree.

**Comment by otavio** [comment]
This issue was fixed on #80. @S-Chinthana please give it a go and reopen this issue if need.

**Comment by S-Chinthana** [comment]
Thanks a lot, guys, Keep up the good work!

**Comment by S-Chinthana** [comment]
Hi @gustavosbarreto  and @otavio ,

I think the pagination option is only working on the session page. On the devices page, it's not working. After adding the 11th device into the shell hub server. Devices list only showing first 10 devices. I think the main issue is still there.
